import os
from pathlib import Path
from dotenv import load_dotenv

# Load .env file from the root directory of the workspace
env_path = Path(__file__).resolve().parent.parent / '.env'
load_dotenv(dotenv_path=env_path)

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
MODEL = os.getenv("MODEL", "gemini-3.1-flash-live-preview")

# Audio Configuration
INPUT_SAMPLE_RATE = 16000   # Expected by Gemini Live API (16kHz PCM)
OUTPUT_SAMPLE_RATE = 24000  # Generated by Gemini Live API (24kHz PCM)
CHANNELS = 1                # Mono
CHUNK_SIZE = 1024           # Frames per buffer
